services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env # Load environment variables from a file
    depends_on:
      - db
volumes:
  data:
